version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:00"
    labels: [ "github_actions" ]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:00"
    labels: [ "dependencies" ]