name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"

permissions:
  contents: write

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22

      - name: Build
        run: go run -v .

      - name: Push
        run: |
          git push origin --delete clash || true
          git checkout --orphan clash
          
          mv *.yaml $RUNNER_TEMP
          git rm -rf .
          mv $RUNNER_TEMP/*.yaml .
          
          git add .
          git commit -m "Update rules"
          git push origin clash
